/**
 * Auth Actions
 */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const LOGOUT = 'LOGOUT';

export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_UP_USER_START = 'SIGN_UP_USER_START';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_FAIL = 'SIGN_UP_USER_FAIL';

/**
 * Offers
 */
export const FIND_OFFERS = 'FIND_OFFERS';
export const FIND_OFFERS_START = 'FIND_OFFERS_START';
export const FIND_OFFERS_FAIL = 'FIND_OFFERS_FAIL';
export const FIND_OFFERS_SUCCESS = 'FIND_OFFERS_SUCCESS';

export const ADD_CHOSEN_OFFER = 'ADD_CHOSEN_OFFER';
export const ADD_CHOSEN_OFFER_START = 'ADD_CHOSEN_OFFER_START';
export const ADD_CHOSEN_OFFER_SUCCESS = 'ADD_CHOSEN_OFFER_SUCCESS';
export const ADD_CHOSEN_OFFER_FAIL = 'ADD_CHOSEN_OFFER_FAIL';

/** 
 * Area Actions
 */
export const GET_AREAS = 'GET_AREAS';
export const GET_AREAS_START = 'GET_AREAS_START';
export const GET_AREAS_SUCCESS = 'GET_AREAS_SUCCESS';
export const GET_AREAS_FAIL = 'GET_AREAS_FAIL';

/** 
 * Get Data
 */
export const GET_LIST_DATA = 'GET_LIST_DATA';
export const GET_LIST_DATA_START = 'GET_LIST_DATA_START';
export const GET_LIST_DATA_SUCCESS = 'GET_LIST_DATA_SUCCESS';
export const GET_LIST_DATA_FAIL = 'GET_LIST_DATA_FAIL';

/**
  * User Actions
  */
export const GET_USER_CHATS = 'GET_USER_CHATS';
export const GET_USER_CHATS_START = 'GET_USER_CHATS_START';
export const GET_USER_CHATS_SUCCESS = 'GET_USER_CHATS_SUCCESS';
export const GET_USER_CHATS_FAIL = 'GET_USER_CHATS_FAIL';
