/**
 * Auth Actions
 */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_START = 'LOGOUT_USER_START';
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
