# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GetInMobileApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GetInMobileApp
pod 'React', :path => '../node_modules/react-native', :subspecs => [
'DevSupport']
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end
